# Site
name: 'Travel Buddi'
title: 'Travel Buddi'
description: 'A travel blog that shows the magic of exploring the world.'
logo: 'assets/images/desert_island.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://travelbuddi.github.io'
# disqus: 'demowebsite'
# email: 'wowthemesnet@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    franzi:
      name:           Franzi
      site:           https://travelbuddi.github.io/
      avatar:         assets/images/franzi.jpeg
      bio:            "Hallo zusammen, ich bin Franzi! <br> Mit 25 Jahren habe ich schon einiges von der Welt gesehen: von Australien 端ber Amerika bis hin zu S端damerika. Seit zwei Jahren nenne ich Wien mein Zuhause. Unser j端ngstes Abenteuer? Einen Mini Van in einen Camper verwandeln! Begleite mich auf meinen Reisen und lass dich von meiner Leidenschaft f端r neue Orte und Erfahrungen anstecken."
      #email:          wowthemesnet@gmail.com
      #twitter:        https://twitter.com/wowthemesnet

    jonas:
      name:           Jonas
      site:           https://yleisnero.github.io
      avatar:         assets/images/jonas.jpeg
      bio:            "Hi ich bin Jonas <br> 25 Jahre alt <br> Programmierer und Reisender aus Wien"
      #email:          fakemail@gmail.com
      #twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jonas
      avatar: /assets/images/jonas.jpeg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]